# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehMaster',
            fields=[
                ('Veh_Reg_No', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Registration No')),
                ('Veh_Make', models.CharField(max_length=15, verbose_name="Vehicle's Make")),
                ('Veh_Model', models.CharField(max_length=15, verbose_name="Vehicle's Model")),
                ('Veh_Year', models.IntegerField(blank=True, null=True, verbose_name='Year Manufactured')),
                ('Veh_Pur_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('Veh_Pur_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('Veh_Sale_date', models.DateField(blank=True, null=True, verbose_name='Sales Date')),
                ('Veh_Sale_price', models.IntegerField(blank=True, null=True, verbose_name='Sales Price')),
                ('Veh_Seats', models.IntegerField(blank=True, null=True, verbose_name='No of Seats')),
                ('Veh_Horsepower', models.IntegerField(blank=True, null=True, verbose_name='Power CC')),
                ('Veh_Colour', models.CharField(blank=True, max_length=20, null=True, verbose_name='Colour')),
                ('Veh_Fuel_Type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fuel Type')),
                ('Veh_Engine_No', models.CharField(blank=True, max_length=20, null=True, verbose_name='Engine No')),
                ('Veh_Chassis_No', models.CharField(blank=True, max_length=20, null=True, verbose_name='Chassis No')),
                ('Veh_Status', models.CharField(max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='VehWorkOrder',
            fields=[
                ('Work_Order_No', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Work_Type', models.CharField(max_length=25, verbose_name='Tyep of Work')),
                ('Work_Invoice_Ref', models.CharField(max_length=25, verbose_name='Work Invoice No')),
                ('Work_Odometer', models.IntegerField(blank=True, null=True, verbose_name='Odometer Reading')),
                ('Work_Man_Name', models.CharField(blank=True, max_length=25, null=True, verbose_name="Expert's Name")),
                ('Work_Details', models.CharField(max_length=200)),
                ('Work_Date', models.DateField(blank=True, null=True, verbose_name='Work Order Date')),
                ('Work_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Work_Remaks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('Work_Reg_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehMaster', verbose_name='Registration No')),
            ],
        ),
    ]
