# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehWorkInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_No', models.CharField(max_length=25, verbose_name='Invoice No')),
                ('Inv_Date', models.DateField(verbose_name='Invoice Date')),
                ('Inv_Customer_Name', models.CharField(max_length=30, verbose_name='Customer Name')),
                ('Inv_Customer_Address1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address Line 1')),
                ('Inv_Customer_Address2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address Line 2')),
                ('Inv_Customer_City', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('Inv_Customer_Contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No')),
                ('Inv_Charge_Type', models.CharField(blank=True, max_length=35, null=True, verbose_name='Charge Type')),
                ('Inv_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Inv_VAT_Persent', models.IntegerField(blank=True, null=True, verbose_name='VAT Persentage')),
                ('Inv_Order_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehWorkOrder', verbose_name='Work Order No')),
            ],
        ),
    ]
