# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehTyres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tyre_Tracking', models.CharField(max_length=25, verbose_name='Tyre No')),
                ('Tyre_Date', models.DateField(verbose_name='Tyre Date')),
                ('Tyre_Shop', models.CharField(max_length=30, verbose_name='Tyre Shop')),
                ('Inv_Customer_Contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No')),
                ('Tyre_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Tyre_OSF', models.IntegerField(blank=True, null=True, verbose_name='OSF')),
                ('Tyre_NSF', models.IntegerField(blank=True, null=True, verbose_name='NSF')),
                ('Tyre_OSR', models.IntegerField(blank=True, null=True, verbose_name='OSR')),
                ('Tyre_NSR', models.IntegerField(blank=True, null=True, verbose_name='NSR')),
                ('Tyre_Reg_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehMaster', verbose_name='Registration No')),
            ],
        ),
        migrations.RenameField(
            model_name='vehinvoice',
            old_name='Inv_Order_No',
            new_name='Work_Order_No',
        ),
    ]
